version: '3.8'
services:
  #PHP Service
  app:
    build:
      args:
        user: davidleekc
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ewallet
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ewallnet

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - ewallnet
     
  #MySQL Service
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:    
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - ewallnet
 
#Docker Networks
networks:
  ewallnet:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local